#!/usr/bin/env bash
#
# Convert things that look like URLs and turn them into HTML URLs.
#
# This is gross lol but `ansi2html -a` didn't work well with parenthesis.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 20, 2025
# License: MIT

url_re='^(.*)\((http[^)]+)\)(.*)'

while IFS= read -r line; do
	if [[ $line =~ $url_re ]]; then
		before=${BASH_REMATCH[1]}
		url=${BASH_REMATCH[2]}
		after=${BASH_REMATCH[3]}

		printf '%s(<a href="%s">%s</a>)%s\n' \
		    "$before" \
		    "$url" "$url" \
		    "$after"
	else
		echo "$line"
	fi
done
