#!/usr/bin/env bash

make-ansi() {
	echo '---' | ./tools/bmd
	echo
	./render-ansi -H
}

template=$(< index.html.template)
html=$(make-ansi | ansi2html -p | ./tools/linkify)

echo "${template/'{{ CONTENT }}'/"$html"}"
